import { getEkoAnalyticsSnippet } from '@ekolabs/eko-gallery-react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script
          id="eko-analytics-snippet"
          dangerouslySetInnerHTML={{
            __html: getEkoAnalyticsSnippet(process.env.NODE_ENV === 'production'),
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
